name: A workflow for my Hello World fileX
on: [push]

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Hello world action step 
        uses: ./action-a
        id: hello
        with:
          MY_NAME: "Mona"
